import os

TEST_TYPE = os.getenv("INSTANCE_BEHAVIOR_TEST", "Global Noise")
SAVE_TYPE = (os.getenv("INSTANCE_BEHAVIOR_SAVE", "true") == "true")

SSE_HEARTBEAT_SECONDS = 15
SSE_RETRY_MILLISECONDS = 4000

CORS_ALLOWED_ORIGIN = os.getenv('CORS_ALLOWED_ORIGIN', '*')
CORS_ALLOWED_METHODS = os.getenv('CORS_ALLOWED_METHODS', 'GET, POST, PUT, DELETE, OPTIONS')
CORS_ALLOWED_HEADERS = os.getenv('CORS_ALLOWED_HEADERS', 'Content-Type, Authorization')
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'false').lower() == 'true'
